"""empty message

Revision ID: 21bef56dd63a
Revises: 470b52b60c0c
Create Date: 2023-04-25 23:57:51.692351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21bef56dd63a'
down_revision = '470b52b60c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_has_smell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_gpt', sa.Integer(), nullable=True),
    sa.Column('id_smell', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('detalhe', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('requirement_smell')
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historia_input', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('historia_output', sa.String(length=256), nullable=True))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('historia_output')
        batch_op.drop_column('historia_input')

    op.create_table('requirement_smell',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('detalhe', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('smells')
    op.drop_table('gpt_has_smell')
    # ### end Alembic commands ###
