"""empty message

Revision ID: 27480910c33c
Revises: dbd9807c5d80
Create Date: 2023-06-04 11:55:46.043111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27480910c33c'
down_revision = 'dbd9807c5d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historia_input', sa.String(length=5000), nullable=True),
    sa.Column('historia_output', sa.String(length=5000), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrucao_prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrucao', sa.String(length=5000), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('detalhe', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    op.drop_table('historias')
    op.drop_table('smells')
    with op.batch_alter_table('gpt_has_smell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao_smell', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpt_has_smell', schema=None) as batch_op:
        batch_op.drop_column('descricao_smell')

    op.create_table('smells',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('detalhe', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('historia_input', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('historia_output', mysql.VARCHAR(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('usuario')
    op.drop_table('smell')
    op.drop_table('instrucao_prompt')
    op.drop_table('historia')
    # ### end Alembic commands ###
