"""empty message

Revision ID: 470b52b60c0c
Revises: 8d5c44c8a516
Create Date: 2023-04-25 00:53:16.045363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470b52b60c0c'
down_revision = '8d5c44c8a516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_smell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('detalhe', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_smell')
    # ### end Alembic commands ###
