"""empty message

Revision ID: 9a2fd4478684
Revises: e25c4c33fe6a
Create Date: 2023-05-27 17:43:16.120351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a2fd4478684'
down_revision = 'e25c4c33fe6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.alter_column('historia_input',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.alter_column('historia_input',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
