"""empty message

Revision ID: cd764f6787fb
Revises: 
Create Date: 2023-06-04 14:52:18.379623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd764f6787fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_has_smell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_gpt', sa.Integer(), nullable=True),
    sa.Column('id_smell', sa.Integer(), nullable=True),
    sa.Column('descricao_smell', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historia_input', sa.String(length=5000), nullable=True),
    sa.Column('historia_output', sa.String(length=5000), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrucao_prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrucao', sa.String(length=5000), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('detalhe', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('smell')
    op.drop_table('instrucao_prompt')
    op.drop_table('historia')
    op.drop_table('gpt_has_smell')
    # ### end Alembic commands ###
