"""empty message

Revision ID: e9e9acc822a0
Revises: 21bef56dd63a
Create Date: 2023-04-26 00:05:32.907334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9e9acc822a0'
down_revision = '21bef56dd63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.alter_column('historia_output',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.alter_column('historia_output',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
